Repository mokumoku-lovers/moku-moku-frontend, pull requests merged in 2021-11, with the labels that each got.

#67 Feature/show answer button logic/62
  src/components/StudyCard/StudyCard.js
  src/components/UI/CardButtons/CardButtons.js
  src/components/UI/CardButtons/CardButtons.module.css
  src/pages/Study/Study.js
  src/pages/Study/Study.module.css
Labels: enhancement, Task

#66 Fix/user profile page/42
  src/components/UI/Avatar/Avatar.js
  src/components/UI/UserProfileCard/UserProfileCard.module.css
  src/pages/UserProfile/UserInfoSection/UserInfoSection.js
  src/pages/UserProfile/UserInfoSection/UserInfoSection.module.css
  src/pages/UserProfile/UserProfile.js
  src/pages/UserProfile/UserProfile.module.css
Labels: Task, fix

#68 Feature/card page/41
  src/App.js
  src/components/StudyCard/StudyCard.js
  src/components/StudyCard/StudyCard.module.css
  src/components/UI/CardButtons/CardButtons.js
  src/components/UI/CardButtons/CardButtons.module.css
  src/pages/Study/Study.js
  src/pages/Study/Study.module.css
Labels: enhancement, Story

#72 Feature/add card page form/70
  src/components/UI/TextArea/TextArea.module.css
  src/pages/AddCardPage/AddCardPage.js
  src/pages/AddCardPage/AddCardPage.module.css
  src/pages/AddCardPage/AddCardPageForm/AddCardPageForm.js
  src/pages/AddCardPage/AddCardPageForm/AddCardPageForm.module.css
Labels: enhancement, Task
