Repository mokumoku-lovers/moku-moku-frontend, pull requests merged in 2022-10, with the labels that each got.

#112 Refactor/userpage layout/108
  src/components/NavBar/AuthNav.js
  src/components/NavBar/NavBar.module.css
  src/pages/UserProfile/UserCardSection/UserCardSection.js
  src/pages/UserProfile/UserCardSection/UserCardSection.module.css
  src/pages/UserProfile/UserProfile.js
  src/pages/UserProfile/UserProfile.module.css
Labels: Task

#113 Feature/edit user form validation/63
  src/features/user/userSlice.js
  src/pages/ProfileEditingPage/GeneralInfoForm/GeneralInfoForm.js
  src/pages/ProfileEditingPage/ProfileEditingPage.js
  src/pages/ProfileEditingPage/ProfileEditingPage.module.css
Labels: Story, Task, API

#111 Feat/400 token redirect on expiration/105
  src/app/checkToken.js
  src/app/store.js
  src/components/ProfileCard/ProfileCard.js
  src/features/auth/authSlice.js
  src/features/deckTitle/deckSlice.js
  src/features/user/userSlice.js
Labels: enhancement, Task
